### ISSUE TITLE
Greenshot 1.3.277 (Pre-Release) - Installation Routine Issue

### ISSUE THREAD

**Issue by ll4mat** [greenshot/greenshot#546]
Hi There

Just tested the pre-release candidate (1.3.277). The following was found:

When the installer is started in user scope, "C:\<username>\AppData\Local\Greenshot" is suggested as the installation directory. If the installer is started as admin (elevated), "C:\Program Files\Greenshot" is suggested as the installation directory. As far as good.

In both cases, however, the corresponding registry key containing the version information, uninstall-strings, installdate and such is created in HKCU hive "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Greenshot_is1", which - for several reasons - is bad.

On a installation in admin context (machine-based), i expect the corresponding registry key to be created either under ‘HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall’ or under ‘HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall’ where it belongs to, and not in HKCU. 

For an installation in user-scope HKCU is fine. 
For an installation in machine-scope, it just sucks.

**Comment by LCI-Kevin-LAURENT** [comment]
Hi, 
I find myself in the same situation. 
After deploying greenshot 1.3.277 in admin on workstations, the installation files are located in "C:\Program Files\Greenshot" however the registry key is not in the right place because it is in HKU  : 
[HKEY_USERS\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Uninstall\Greenshot_is1].
Instead of being in HKLM as suggested in the post above
Which means that Windows does not even see the software as installed because it does not appear in the list of installed programs.

**Comment by chbwien** [comment]
And there is another bug: If you have already installed the program as admin in c:\program and restart the installer as user (because you simply forgot to elevate the installer, which is really unusual), the old settings will be used (destination c:\program) and the installer will simply fail due to lack of write permissions in the destination.

**Comment by bratensauce** [comment]
I just installed the final version 1.3.290 and unfortunately this issue is still present.

Not nice at all. I was looking forward for this release for the Win11 upgrade issue to be fixed but I guess I cannot deploy this version with such an ugly bug.

<img width="1888" height="876" alt="Image" src="https://github.com/user-attachments/assets/1a728eb3-1e61-4424-bb3e-4a92549a06a3" />

**Comment by FF-Brown** [comment]
@bratensauce Can't be happy/grateful that there's a new release? Chill, dude. Bugs will get fixed. If you're not happy with the speed, fix it yourself. In the meantime be nice to the maintainers, we wouldn't have this release without their work.

**Comment by jklingen** [comment]
This must have slipped through when we were looking for issues specific to the new version - we'll have a look at it.

But don't worry, our plan is to publish smaller releases in shorter intervals in the future.

**Comment by jklingen** [comment]
The issue should be fixed as of 1.3.293 (change not merged yet, so the version is marked unstable and unsigned) - could you give it a try, please?
https://getgreenshot.org/version-history/

**Comment by bratensauce** [comment]
Cool thanks. I've tested it. Unfortunately it doesn't quite work yet.
It does now create a Greenshot folder in the HKLM registry:

<img width="1350" height="464" alt="Image" src="https://github.com/user-attachments/assets/91b2be45-5be7-4bb7-80d4-908cf31a914b" />

But it's missing many things like "DisplayVersion". This means, the software appears in "Add and Remove Programs", but without version:
<img width="756" height="452" alt="Image" src="https://github.com/user-attachments/assets/0a90e432-57a8-402b-a851-049a165384b0" />

And the wrong folder in .DEFAULT is still being created:

<img width="1574" height="973" alt="Image" src="https://github.com/user-attachments/assets/b9dec983-96e9-464b-96ac-9118ac724e88" />

There is also no folder/link created in the Start Menu anymore with version 1.3.293 when installing with admin rights.

It also tries to open the "Thank you for using Greenshot" website after the installation which is for a silent installation not optimal and can hang up installers. (This one is not an issue for me, but maybe for others.)

Thanks again for your effort. @jklingen

**Comment by jklingen** [comment]
Thanks for re-testing this 👍 
Earlier this day, we built another pre-release that fixes the problems with installation in system context (at least confirmed by another user in #619)
If you want to try it: https://github.com/greenshot/greenshot/releases/tag/v1.3.292

(Please don't be confused by the build number being lower than the one I have built yesterday - we just noticed that our new workflow for build & deploy mixes up build numbers if used from a branch 🙈

**Comment by bratensauce** [comment]
Awesome! I've just tested it again and I can confirm, all my reported problems are fixed with this release 1.3.292. Thanks @jklingen

**Comment by jklingen** [comment]
Fixed with 1.3.292, which is now marked as the latest stable release. Please update if you haven't yet.

@bratensauce Thanks for re-testing and providing quick feedback 👍

**Comment by Gil-s-rouen** [comment]
> Fixed with 1.3.292, which is now marked as the latest stable release. Please update if you haven't yet.
> 
> [@bratensauce](https://github.com/bratensauce) Thanks for re-testing and providing quick feedback 👍

Hello,

I had version 1.2.6.10 installed, and the program appeared in the list of installed programs in Settings/Apps.

I closed Greenshot, launched the installation of version 1.3.292 as administrator. The application is installed and functional, but it still doesn't appear in the list of installed programs (as does version 1.3.290).
Searching the registry for “Greenshot_is1” I find it in the “Computer\HKEY_USERS\S-1-5-21-+++++++++++-++++++++++-+++++++++-++++\Software\Microsoft\Windows\CurrentVersion\Uninstall\Greenshot_is1” branch, where “S-1-5-21-+++++++++++-++++++++++-+++++++++-++++” is the SID of my administrator user.
If I want to uninstall Greenshot, I have to go to the folder “C:\Program Files\Greenshot” and run “unins000.exe”.

The problem is obviously not solved.

Best regards

**Comment by bratensauce** [comment]
@Gil-s-rouen make sure to uninstall previous versions before installing the new one.
I tested it again and it worked again for me with 1.3.292
For our silent deployment I'm using:

`"Greenshot-INSTALLER-1.3.292-UNSTABLE.exe" /VERYSILENT /SUPPRESSMSGBOXES /ALLUSERS /NORESTART /RESTARTAPPLICATIONS /LOADINF="greenshotInstall.inf"`

inf file:
```
[Setup]
Lang=en
Group=Greenshot
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=commandline,dialog
NoIcons=0
SetupType=custom
Components=greenshot,plugins\office,plugins\ocr,plugins\externalcommand
Tasks=startup

```

**Comment by RonnyTNL** [comment]
Hi All this issue is not resolved correctly in 1.3.292.
This was a fresh machine which had never seen Greenshot.

The problem is the uninstall entries are created under the HKCU (in this case for the Admin user) but it should have been under HKLM when installed as admin. It also fails to show up in the Start Menu of a regular user account when installed as Administrator (which both are not expected when installed global/machine wide).

Repro:
Sign in to a limited account and run the installer "Run as Administrator".
After install try to find the application in the start menu of the regular user (it's not there).
Try to find the application via CMD+R -> appwiz.cpl and see if it's installed and/or uninstallable it's not there (because of the HKCU mixup should have been in HKLM when installed machine wide/Program files).

**Comment by jklingen** [comment]
We'll check again.

**Comment by bratensauce** [comment]
Tested what @RonnyTNL was reporting and yes, was able to reproduce it.
So the problem is solved for silent installations running with parameters but not for manual "run as administrator" installations.
I suggest to use the workaround by running it as a silent installation from an elevated CMD (example above) for now, until it is fixed.

**Comment by jklingen** [comment]
Could someone please try whether this test (!) release installs as expected? https://github.com/greenshot/greenshot/releases/tag/bug%2F546-admin-install

It allows to select for all-users vs. current-user installation (and asks for elevation only if needed), and, as far as I can see, all the registry keys end up where they should.

Please note: if there is an existing installation (i.e. the update scenario), InnoSetup won't display the selection dialog and just use the same installation mode as the existing installation. This is InnoSetup's default behavior.

**Comment by RonnyTNL** [comment]
> Could someone please try whether this test (!) release installs as expected? https://github.com/greenshot/greenshot/releases/tag/bug%2F546-admin-install
> 
> It allows to select for all-users vs. current-user installation (and asks for elevation only if needed), and, as far as I can see, all the registry keys end up where they should.
> 
> Please note: if there is an existing installation (i.e. the update scenario), InnoSetup won't display the selection dialog and just use the same installation mode as the existing installation. This is InnoSetup's default behavior.

Sure I'll give it a few spins on a VM.
I"ll test install as admin system wide, and as User for limited and admin see where we end up.
Thanks for the quick fix.

**Comment by RonnyTNL** [comment]
@jklingen awesome \m/

Install as Admin => System wide works as expected. (HKLM + Start Menu OK, also registry DisplayVersion is set).
Install as Limited User => %userprofile% works as expected (HKCU + Start Menu OK, also registry DisplayVersion is set).
Install as Admin User => %userprofile% works as expected (HKCU + Start Menu OK, also registry DisplayVersion is set).

All tests done on a clean VM snapshot with rollbacks between each test (hence 100% no left-overs).

@bratensauce can you confirm the correct behavior on your end also?

**Comment by jklingen** [comment]
Thanks so much @RonnyTNL . 🎉 

We have just pushlished the bugifx release 1.3.296

**Comment by nielsmolenaar1** [comment]
just downloaded 1.3.296.
Seems like it is forcing to choose between "install for me" and "install for all"
/S, /VERSILENT, /ALLUSERS=0 or other parameters don't work for me.
 What am I missing?
